version: '2'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres: