spring:
  application:
    name: currencies-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    default-schema: public
    parameters:
      default-schema-prefix: public.

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080
  forward-headers-strategy: framework
  error:
    include-message: always
